### ISSUE TITLE
Some feature suggestions which would make this addon totally badass

### ISSUE THREAD

**Issue by janvandyk** [tiansh/classical-search-bar#10]
Hey there,

First of all: I'm very glad this web-extension exist at all, because I find these "new" search buttons horrible, especially since they are mandatory. So thank you!
Nevertheless this extension (still?) lacks of some functionalities to make it a perfect replacement for the configuration I was used to have back then with the following xul-addon (which still works with waterfox and probably firefox-esr):
https://github.com/Baton34/organize-search-engines

So here comes my list of suggestions:
1. Make search engines organizable in subfolders
2. Have an "add search engine" button in the
  a) search-engine/CSB button
  b) context menu
3. make search engines accessible in the context menu of text-selections

There actually exists a web-extension which provides all these functionalities:
https://addons.mozilla.org/de/firefox/addon/selection-context-search/
Unfortunately it's not open source and does not provide the "classic search bar" Button like this addon :-(

There also is another "context search" web-extension, that has an interesting approach to implement the suggested features. It makes use of the built-in bookmark folders and  [smart keyword bookmarks](https://support.mozilla.org/en-US/kb/how-search-from-address-bar). :
https://github.com/NumeriusNegidius/Context-Search
And it is open source! :-)
Maybe it's somehow possible to merge CSB with this one. I will also post a text to their issue tracker with a link to this one here...

Thank you and best regards
Jan

**Comment by tiansh** [comment]
1. What do you mean by "organizable in subfolders"? Do you prefer the menu of switching search engines may contains sub menus?
2. Adding buttons should be a nice feature. But it is too complex and I'm not sure if it is really necessary.
3. Currently, Firefox has a "search xyz with CSB (your currently default search engine)" option in context menu as built in. Is this what you want?

**Comment by duncaner** [comment]
Here's an example of what janvandyk meant in his first point. Having folders and separators can make the engine search list shorter and easier to use.

This is from the extension mentioned running in old Firefox versions (here Waterfox).

![image](https://user-images.githubusercontent.com/23550080/58880264-d455e380-86d7-11e9-91d2-2dbd175f16a0.png)

**Comment by tiansh** [comment]
Folders had added as version 2.0

**Comment by duncaner** [comment]
What a nice surprise!

Thank you, this is a great addition :-)

**Comment by tiansh** [comment]
Context menu support had also added in version 2.1.0.

Since watching for opensearch on every page is too complete and needs <all_url> permission. I'm not considered implement it. It had also be tracked in issue #8. So I would close this issue as its done.
