### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Neytrino-OnLine** [tiansh/classical-search-bar#13]
I am not sure how to correctly create a pull request, so i did it here...

**Comment by Neytrino-OnLine** [comment]
{
"extensionName": {
"message": "Classical Search Bar",
"description": "Name of the extension; Should be kept as is when localizing."
},
"extensionDescription": {
"message": "Симулирует классическую панель поиска, добавляя кнопку для переключения поисковых систем.",
"description": "Description of the extension."
},
"extensionButtonTitle": {
"message": "Искать через %s",
"description": "Title of the extension button. %s would be replaced to current selected search provider's name"
},
"addButton": {
"message": "Добавить",
"description": "A button for adding search engine in option page"
},
"resetButton": {
"message": "Восстановить настройки по умолчанию",
"description": "A button for reset search engine list in option page"
},
"resetButtonSecondTime": {
"message": "Нажмите ещё раз для подтверждения",
"description": "A button for confirm reset action"
},
"configTitleName": {
"message": "Название",
"description": "Option title for the name of a search engine"
},
"configTitleHomePage": {
"message": "Домен",
"description": "Option title for the home page URL of a search engine"
},
"configTitleSearchUrl": {
"message": "Поисковый URL",
"description": "Option title for the searching URL of a search engine"
},
"configTitleSearchUrlPostParameters": {
"message": "Дополнительные параметры",
"description": "Option title for the post parameters of searching URL"
},
"configTitleEncoding": {
"message": "Кодировка",
"description": "Option title for the input encoding of search terms"
},
"configSearchUrlDescription": {
"message": "Используйте {searchTerms} для подстановки текста в поисковый запрос",
"description": "Description of the URL of a search engine; {searchTerms} part should be kept as is when localizing"
},
"configTitleIcon": {
"message": "Иконка",
"description": "Option title for the icon of a search engine"
},
"browseButton": {
"message": "Обзор...",
"description": "Button for selecting icon file for search engine option"
},
"configTitleStatus": {
"message": "Видимость",
"description": "Option title for the status of a search engine (enable / disabled)"
},
"configStatusEnabled": {
"message": "Отображать",
"description": "Option description for the enable status of a search engine"
},
"moveUpButton": {
"message": "Поднять",
"description": "Button for moving a search engine one item up in the list"
},
"moveDownButton": {
"message": "Опустить",
"description": "Button for moving a search engine one item down in the list"
},
"saveButton": {
"message": "Сохранить",
"description": "Button for confirming the editing of selected search engine"
},
"removeButton": {
"message": "Удалить",
"description": "Button for removing a search engine from the list"
},
"backupPanelTitle": {
"message": "Настройки",
"description": "Title for the import / exporting section"
},
"importOverwriteButton": {
"message": "Импорт с замещением настроек",
"description": "Button for import settings from a file"
},
"importAppendButton": {
"message": "Импорт с добавлением настроек",
"description": "Button for import settings from a file"
},
"importFailedAlert": {
"message": "При импорте настроек, что-то пошло не так.",
"description": "This text will be alerted to user if import failed"
},
"exportButton": {
"message": "Экспорт настроек",
"description": "Button for export settings to a file"
},
"themePanelTitle": {
"message": "Оформление",
"description": "Title for theme section"
},
"themeAutoText": {
"message": "Авто",
"description": "The extension should try to detect browser theme automatically."
},
"themeDarkText": {
"message": "Тёмное",
"description": "The extension should use dark theme."
},
"themeLightText": {
"message": "Светлое",
"description": "The extension should use light theme."
}
}

**Comment by tiansh** [comment]
Should I use Светлая/Тёмная or Светлое/Тёмное? Firefox seems using Светлая/Тёмная, so I would prefer it if it is OK. Also, I added these three items need to translate,
```json
{
  "executeBrowserActionCommand": {
    "message": "Show the Popup",
    "description": "Title for config keyboard shotcut of execute browser action"
  },
  "searchProviderPrevCommand": {
    "message": "Change the Default Search Engine ↑",
    "description": "Title for config keyboard shotcut of changing to prev search provider"
  },
  "searchProviderNextCommand": {
    "message": "Change the Default Search Engine ↓",
    "description": "Title for config keyboard shotcut of changing to next search provider"
  }
}
```
I tried to use machine translate and some search, is these OK?

```
показать всплывающие окна
Изменение поисковой системы↑
```

**Comment by tiansh** [comment]
v1.6.12 is on AMO now. Please feel free to comment this issue in case anything went to wrong.

**Comment by tiansh** [comment]
I had added folders and context menu to newer version. Texts used are based on machine translation. Please tell me if any translation needs improve or even doesn't make sense.
