### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by goodclue** [tiansh/classical-search-bar#14]
Great extension. Work fine. Could be possible to have an option to force a search to open a new TAB (or Windows) rather than use the current open TAB ?

**Comment by tiansh** [comment]
This is controlled by `browser.search.openintab` in `about:config`. WebExtension may not read / write `about:config`, so you have to config it manually.

**Comment by tiansh** [comment]
OK, it seems that WebExtension may control this value. I'm not sure if this should be added here. Just leave it open...

**Comment by tiansh** [comment]
I have double checked the API. The api seems too confusing to me. And adding an option while say "This option currently controlled by another extension" would make user confuse. So I would not add this option in my extension. Luckily, anyone need it may simply toggle `browser.search.openintab` in `about:config`.
