### ISSUE TITLE
Broken with firefox 79

### ISSUE THREAD

**Issue by jborme** [tiansh/classical-search-bar#17]
After updating to firefox 79.0, the add-on stops working.

It is still possible to perform a search with the search engine that is selected. 
Attempt to change the search engine does not work (the icon does not change and the new engine is not selected) and firefox starts consuming 100% of a CPU indefinitely.

This is what shows up in top after attempting to change the search engine.
```
 PID UTIL.     PR  NI    VIRT    RES    SHR S  %CPU  %MEM    TEMPS+ COM.                          
9398 jerome    20   0 2995956 376624 164568 R  77,1   0,3   2:32.34 MainThread                    
9512 jerome    20   0 9220876 426572 109500 S  50,2   0,3   1:33.24 WebExtensions                 
```

**Comment by tiansh** [comment]
Thanks for your feed back. An update will be released in 1 day. Sorry for any inconvenience.

Firefox had limited its storage quota for sync storage. The configuration used up the quota and failed to write new configs. The extension was confused by the failing of config writing and trying it again and again which caused a high CUP load. As far as what I see. The only thing I can do is moving from sync storage to local storage. The extension would work normal but cannot sync configurations between users' Firefox setups.

**Comment by tiansh** [comment]
The newer version had released on AMO. Update to 1.7. And it should work again.
