### ISSUE TITLE
Possibility of combining engines to a folder

### ISSUE THREAD

**Issue by Baton34** [tiansh/classical-search-bar#18]
I use waterfox now for only one reason - it have "Organize search engines" addon, because i have many search engines and using it without folder is terrible.
Now i found your beautiful addon and it needs one more changing to be excellent:
Its would be awesome if engines may be arranged in folders like it was in "Organize search engines" addon in ff xul era.
Can you implement it?

**Comment by tiansh** [comment]
You are not the only one who asked this feature. I just didn't have much time working on it.

**Comment by tiansh** [comment]
![with a add folder button](https://user-images.githubusercontent.com/6500326/97974982-4eeccc00-1dc0-11eb-9159-b3852164c11b.png)

I'm working on it. But I have no idea where should I place the "Add Folder" button...

Any ideas?

**Comment by Baton34** [comment]
Maybe on the right side and use only "Name" input.
ps: I realised folder structure by myself (based on your addon), but it import search engines (names and icons) from browser.
https://github.com/Baton34/Organize-Search-Engines2

**Comment by tiansh** [comment]
btw, I'm updating locale files with machine translation... Is these acceptable?

![Choose type (ru)](https://user-images.githubusercontent.com/6500326/98096101-3b566980-1e83-11eb-82c1-3498819aa8d3.png)

**Comment by tiansh** [comment]
The new version had released on AMO.

**Comment by Baton34** [comment]
> Is these acceptable?

yes, its Ok.
