### ISSUE TITLE
Import/Export settings

### ISSUE THREAD

**Issue by ElektroStudios** [tiansh/classical-search-bar#2]
Please take into account big search provider lists like for example this:

![](https://i.imgur.com/6JcCqTk.png)

It takes a lot of time to research the query parameters for each website, generate their favicons and then input all the data into your extension, imagine that a user needs to install Firefox on another machine, or that in the current machine for any kind of data corruption issue the current search providers list is lost, without an export/import feature that user will need to redo all the work (if that user didn't made any backup of the folder).

I think that is the main reason why other extensions gives an export/import setting, I mean to facilitate copying the same settings in multiple machines or to avoid data lose in the current machine.

Thanks for read.

**Comment by ElektroStudios** [comment]
Of course the import setting should overwrite current settings!

OpenXML is a known file format to represent search providers:

`<SearchPlugin xmlns="http://www.mozilla.org/2006/browser/search/" xmlns:os="http://a9.com/-/spec/opensearch/1.1/">
<os:ShortName>GameFAQS</os:ShortName>
<os:Description>GameFAQS Search</os:Description>
<os:InputEncoding>UTF-8</os:InputEncoding>
<os:Image width="16" height="16">data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACEUlEQVQ4jaXTzU8TQRiAcf5EjcaPQLv92kaKUT40RM9w0NSTVA56MBygdwnQEmu0VESJCaSlYOMJSluIXXa7253dne3jAcLSQDTGSZ5k5vI7vHlnQE3A/zRw8TE+BmtFEAJc988BFIvtfmB5mX86E+PZAEgNQ6HgUC7vs7W1z85Og0rlkHK5fqm93SbfvtYYGiwEQFKFhw+6RCNV4rEaEWWPcKiKEt69srt3KsRjBwGQTsOXdcnGhmTxnUFSNf4+RPUMSKqQz4PneQAsLa2jhOu8SNsUCpDL9c7L5yG3Ao8fHaMm/FPg/ghUyj2EEABMT62SiJ9Qq4Hv+7iui+M4CCGQUmJ2OijhbZJq7xR4+gQMw6Pb7SKlJBZdZWy0jW338H0fX0ps28ayLDzPY3PzJ4n4QbAHrzIghMCyLI6OdG7e+MBIqsv01Bbh0FuikSzZ7HeklADMzn4kqdYDoPAeLMtCSsn8/DpDg/VLA1tYaOG6LlJKJidzjKScAKjVfHRdx/M85uY+MTH+g8wMZDIw8xLevIZmEwzDoN3WiEaqpIb9ADisO2iadpaOED4nmnmerpsYhoFt25RKOyTVRv9f0NoOpmnS6XSwLOv8fjHTNAF4/izP8L1WP/C51KLRPKbR+HVlzWabVktjcXGT69dWUBNmPzA2ahEaKhJRiijhy0WUNUKhIrdvbROLirPV76Em4Dc8/DkH6r+NQwAAAABJRU5ErkJggg==</os:Image>
<SearchForm>https://gamefaqs.gamespot.com</SearchForm>
<os:Url type="text/html" method="GET" template="https://gamefaqs.gamespot.com/search" resultDomain="gamefaqs.gamespot.com">
  <os:Param name="game" value="{searchTerms}"/>
</os:Url>
</SearchPlugin>


`

but I think there is no real need to export in that format, your extension just could serialize (export) all the settings with JSON serialization in a single file and then deserialize (import) it.

**Comment by tiansh** [comment]
Added import / export to `master` branch. And I would like to address post request before publish it. You may have a try by install temporary add-on.

**Comment by tiansh** [comment]
Added in version 1.3.0

**Comment by knedel** [comment]
How to import the entire list of search engines with favicons embedded in firefox into this add-on? Is there any method without adding each search engine separately?

**Comment by tiansh** [comment]
@knedel By press the import button and select exported file? Sorry I didn’t catch your question. Anything wrong with this feature?

**Comment by knedel** [comment]
I have a standard search bar with search engines, like this:
![51122420-21651600-181a-11e9-866d-5ac1ba1f9a33](https://user-images.githubusercontent.com/46283252/53499931-b14cdf80-3aa9-11e9-95e1-2d5383548d18.png)

How to import the search engines defined in the search.json.mozlz4 file?
[search.json.mozlz4.zip](https://github.com/tiansh/classical-search-bar/files/2910856/search.json.mozlz4.zip)

I tried to decompress the search.json.mozlz4 file and then import it using the classical-search-bar add-on, but I always get an error "Something went wrong while importing". Is this possible?

**Comment by tiansh** [comment]
@knedel Currently only support the file exported from this extension. Other formats are not supported (at least, yet).
